# Generated by Django 5.0.1 on 2024-10-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=50, verbose_name='مستوى الخبرة'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='financial_goals',
            field=models.CharField(default='Monthly profit target', help_text='الهدف المالي اليومي أو الأسبوعي أو الشهري.', max_length=255, verbose_name='الأهداف المالية'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='market_analysis',
            field=models.CharField(choices=[('technical', 'التحليل الفني'), ('fundamental', 'التحليل الأساسي'), ('mixed', 'مزيج بينهما')], default='technical', max_length=50, verbose_name='تحليل السوق المفضل'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='preferred_assets',
            field=models.CharField(default='Forex', help_text='مثل الفوركس، الأسهم، أو العملات الرقمية.', max_length=255, verbose_name='الأصول المفضلة'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='risk_management',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='نسبة المخاطرة بالنسبة لرأس المال.', max_digits=5, verbose_name='إدارة المخاطر'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trading_hours',
            field=models.CharField(default='9am-5pm', help_text='أوقات التداول المفضلة.', max_length=255, verbose_name='ساعات التداول'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trading_style',
            field=models.CharField(choices=[('day', 'تداول يومي'), ('swing', 'تداول السوينغ'), ('long', 'استثمار طويل الأمد')], default='day', max_length=50, verbose_name='أسلوب التداول'),
        ),
    ]
