# Generated by Django 5.0.1 on 2024-10-30 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_strategy_experience_level_strategy_financial_goals_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='chatgpt_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
