# Generated by Django 5.0.1 on 2024-10-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'نقطة',
                'verbose_name_plural': 'نقاط',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('points_required', models.IntegerField(verbose_name='النقاط المطلوبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'مكافآت',
                'ordering': ['points_required'],
            },
        ),
    ]
